In [1]:
import numpy as np

In [ ]:
a=np.array([1,2,3,4,5,6])# to create array in numpy
b=np.array([7,8,9,10,11,12])
print(a)
print(b)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]


In [3]:
#to know datatype of array
type(a)

numpy.ndarray

# OPERATION SND METHODS

In [4]:
print(a+b)
print(a-b)
print(a*b)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]


In [ ]:
#creating 2d array we to make two 1d array
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [ ]:
#to create 3d array by creating two 2d array in one
a3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
print(a2.shape)#it tells row,coloumn0
print(a3.shape)#it tells matrix,row,coloumn

(2, 3)
(2, 2, 3)


In [8]:
print(a3.ndim)# it tell dimension of array

3


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [13]:
#to create 2d array by random library
np.random.randint(1,21,size=(3,4))

array([[ 8,  4,  2, 13],
       [ 9,  2, 13,  6],
       [ 1, 18, 13, 20]], dtype=int32)

In [14]:
x=np.array([[7,2,3],[3,9,4],[3,4,5,]])
y=np.array([[3,4,5],[3,9,4],[7,2,3]])
print(x*y)

[[21  8 15]
 [ 9 81 16]
 [21  8 15]]


In [15]:
print(x@y)#matrix multiplication

[[ 48  52  52]
 [ 64 101  63]
 [ 56  58  46]]


In [17]:
np.dot(x,y)#same multiplication matrix

array([[ 48,  52,  52],
       [ 64, 101,  63],
       [ 56,  58,  46]])

In [18]:
x.mean()

np.float64(4.444444444444445)

In [19]:
round(x.mean())

4

In [ ]:
print(x.sum())
print(x.var())#varience 
print(x.std())#standard deviation

40
4.469135802469136
2.1140330656044943


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,25))#25 percentile
print(np.percentile(arr,50))#50 percentile(median)
print(np.percentile(arr,75))#75 percentile
